name: Chelsea test

on: push

jobs:
  build:
    name: Rebuild gh-pages document
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      USER_NAME: ${{ github.event.head_commit.author.name }}
      USER_EMAIL: ${{ github.event.head_commit.author.email }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
          token: ${{ secrets.CHELSEA_SECRET }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set github config
        run: |
          git config --local user.email "$USER_EMAIL"
          git config --local user.name "$USER_NAME"
      - name: Rebuild document files
        run: |
          chmod +x ./build.sh
          sh ./build.sh --vse
