name: Chelsea test

on: push

jobs:
  build:
    name: Set up environments
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        python-version: [3.7]
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CHELSEA_SECRET }}
          publish_dir: ./public