name: Chelsea test

on:
  push

jobs:
  build:
    name: Set up environments
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: Build html
        run: |
          chmod +x ./build.sh
          sh ./build.sh
