name: Build Trek document to gh-pages branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
  push:
    branches:
      - master

jobs:
  build:
    name: Rebuild Trek document files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      USER_NAME: ${{ github.event.head_commit.author.name }}
      USER_EMAIL: ${{ github.event.head_commit.author.email }}
      RELEASE_BRANCH: gh-pages
      TOKEN: ${{ secrets.CHELSEA_SECRET }}
    steps:
      - name: Extract source branch name
        shell: bash
        run: echo "##[set-output name=source_br;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_br
      - name: Checkout source branch (${{ steps.extract_br.outputs.source_br }}) repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_REF }}
          token: ${{ env.TOKEN }}
      - name: Set github config and extract source branch last commit id
        run: |
          git config --local user.email "$USER_EMAIL"
          git config --local user.name "$USER_NAME"
          echo "##[set-output name=commit_id;]$(echo `git rev-parse --short ${{ github.event.head_commit.id }}`)"
        id: extract_commit
      - name: Force merge and push to ${{ env.RELEASE_BRANCH }}
        run: |
          git push --force origin $GITHUB_REF:$RELEASE_BRANCH
      - name: Checkout target branch (${{ env.RELEASE_BRANCH }}) repo include submodule
        uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_BRANCH }}
          token: ${{ env.TOKEN }}
      - name: Overwrite .gitignore to unignore build/html files
        run: |
          cp .gitignore.gh-pages .gitignore
          git add .gitignore
          git commit --allow-empty -m "misc: replace .gitignore to .gitignore.gh-pages (${{ steps.extract_commit.outputs.commit_id }})"
          git push -f
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: Rebuild document files
        run: |
          chmod +x ./build.sh
          sh ./build.sh --blcks --trek --vse --token $TOKEN
      - name: Commit and push built files
        run: |
          git add . -A
          git commit --allow-empty -m "misc: rebuild html (${{ steps.extract_commit.outputs.commit_id }})"
          git push
