name: Build Trek document to gh-pages branch

on: 
  push:
    branches:
      - p/3658/chelsea_add_github_action

jobs:
  build:
    name: Rebuild Trek document files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      USER_NAME: ${{ github.event.head_commit.author.name }}
      USER_EMAIL: ${{ github.event.head_commit.author.email }}
    steps:
      - name: Checkout gh-pages repo include submodule
        uses: actions/checkout@v2
        with:
          ref: p/3658/chelsea_test
          fetch-depth: 1
          submodules: true
          token: ${{ secrets.CHELSEA_SECRET }}
      - name: Set github config
        run: |
          git config --local user.email "$USER_EMAIL"
          git config --local user.name "$USER_NAME"
      - name: Rebase gh-pages with master
        run: |
          git pull
          echo "****"
          git branch
          git rebase -s recursive -X theirs refs/remotes/origin/p/3658/chelsea_add_github_action
          cp .gitignore.gh-pages .gitignore
          git add .gitignore
          git commit --allow-empty -m "misc: .gitignore replcate with .gitignore.gh-pages"
          git push -f
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: Rebuild document files
        run: |
          chmod +x ./build.sh
          sh ./build.sh --blcks --trek --vse
      - name: Commit and push built files
        run: |
          git add . -A
          git commit --allow-empty -m "${{ github.event.head_commit.message }}"
          git push
