name: Chelsea test

on: push

jobs:
  build:
    name: Set up environments
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: npm install
        run: |
          npm install
      - name: Build html
        run: |
          chmod +x ./build.sh
          sh ./build.sh
      - name: deploy and publish
        working-directory: ./public
        run: |
           git config --local user.email "chelsea.lo@pentium.network"
           git config --local user.name "chelsealopentinum"
           git add . -A
           git commit -m "misc: Rebuild html"
           git push origin
      