name: Chelsea test

on: push

jobs:
  build:
    name: Rebuild gh-pages document
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    env:
      MY_SECRET: ${{secrets.CHELSEA_SECRET}}
      USER_NAME: ${{GITHUB_ACTOR}}
      USER_EMAIL: chelsea.lo@pentium.network
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: $MY_SECRET
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: Set git config
        run: |
          git config user.email $USER_EMAIL
          git config user.name $USER_NAME
      - name: Rebuild document files
        run: |
          git config user.email $USER_EMAIL
          git config user.name $USER_NAME
          chmod +x ./build.sh
          sh ./build.sh --trek --vse --blcks
      - name: Commit and push built files
        run: |
          git config user.email $USER_EMAIL
          git config user.name $USER_NAME
          git add . -A
          git commit -m "misc: Rebuild html"
          git push
